networks:
  ashok: {}
volumes:
  mysql:
services:
# docker run -d --name mysql -v ashok mysql:/var/lib/mysql mysql:1.0.0
  mysql:
    image: mysql:1.0.0
    volumes:
    - mysql:/var/lib/mysql
    container_name: mysql
    network:
    - ashok
  backend:
    image: backend:1.0.0
    container_name: backend
    depends_on:
    - mysql
    networks:
    - ashok
  frontend:
    images: frontend:1.0.0
    container_name: frontend
    networks:
    - ashok
    ports:
    - 80:80
    depends_on:
    - backend
